name: Build everything
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Compile changed kernel
    # This job runs on self hosted Linux machine
    runs-on: self-hosted
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      #- uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Compile and update repository
        run: |         
         ./compile.sh BOARD="bananapi" BETA="yes" BRANCH="current" KERNEL_ONLY="yes" KERNEL_CONFIGURE="no" CLEAN_LEVEL="make,oldcache" SUBREVISION="."${{ steps.slug.outputs.sha8 }}
         echo "done"
        shell: bash
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Images
          path: output/debs
