name: Build everything
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: self-hosted
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      #- uses: actions/checkout@v2
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(cat VERSION)${{ steps.today.outputs.date }}-${{ steps.slug.outputs.sha8 }}
          release_name: Release v${{ steps.today.outputs.date }}-${{ steps.slug.outputs.sha8 }}
          draft: false
          prerelease: false
      - name: Display the path
        run: ./compile.sh BOARD="bananapi" BRANCH="current" KERNEL_ONLY="no" BUILD_DESKTOP="no" KERNEL_CONFIGURE="no" RELEASE="focal" BUILD_MINIMAL="yes" CLEAN_LEVEL="make,oldcache" SUBREVISION="."$(date --date="tomorrow" +"%j")${GITHUB_SHA}
        shell: bash
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Images
          path: output
