name: image_build_a
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'
      -
        id: image-build
        run: |        

          wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_xfce_desktop.img.xz
          wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_minimal.img.xz
          echo "FILE_PATH=Armbian_21.05.1_Bananapi_buster_current_5.10.34_xfce_desktop.img.xz" >> $GITHUB_ENV

      - 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Armbian*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

