name: image_build_a
on:
  workflow_dispatch:

jobs:
  "A": # short name because GH will expand with the matrix values
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
          - board: Runner 1
            desc: ODROID N2+, cloud image, user-data at /boot (ext4)
            runnerLabel: can-build-arm64
            vars: "CLOUD_IMAGE=yes"
            aaaa: 2

          - board: Runner 2
            desc: Khadas VIM3, cloud image, user-data at /boot (ext4)
            runnerLabel: can-build-arm64
            vars: "CLOUD_IMAGE=yes"
            aaaa: 3
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'
      -
        id: image-build
        run: |        

          wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_xfce_desktop.img.xz
          wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_minimal.img.xz

      - 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Armbian*
          tag: bananapi
          overwrite: true
          file_glob: true

