name: image_build_a
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      -
        run: |
          wget https://www.armbian.com/userdata.csv
          mkdir temp1
          cp userdata.csv temp1/
      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-build-list
        with:
          path: temp1
          key: ${{ runner.os }}-build-${{ env.cache-name }}

  "A": # short name because GH will expand with the matrix values
    needs: [ prepare ]
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        include:
          - board: "Bananapi"
            desc: Mirroring Bananapi
            vars: bananapi
            aaaa: 2

          - board: "Bananapi M2"
            desc: Mirroring Bananapi M2
            vars: bananapim2
            aaaa: 3

    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-build-list
        with:
          path: temp1
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      -
        id: image-build
        run: |        

          cat temp1/userdata.csv | grep "${{ matrix.board }}/" | grep -v nightly | cut -d"|" -f2

          #wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_xfce_desktop.img.xz
          #wget https://dl.armbian.com/bananapi/archive/Armbian_21.05.1_Bananapi_buster_current_5.10.34_minimal.img.xz
          #cat temp1/userdata.csv
      - 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Armbian*
          tag: ${{ matrix.vars }}
          overwrite: true
          file_glob: true

