name: Docker Image CI
on: [push]
jobs:
  build:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the tagged Docker image
        run: ./compile.sh docker
