name: Delete releases
on:
  workflow_dispatch:

jobs:
  Purge:
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - board: bananapi
          - board: zeropi
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true # default: false
          tag_name: ${{ matrix.board }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
