name: Sync rootfs
on:
#  schedule:
#    - cron:  '0 */4 * * *'

  workflow_dispatch:

jobs:

  Prepare:

    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'igorpecovnik' }}
    steps:

      - name: Cut the job into n chunks
        run: |

          mkdir -p temp
          rsync rsync://rsync.armbian.com/dl/_rootfs/ | awk '{ print $5}' | tail -n +3 > temp/rootfs.chunk
          split -d --number=l/10 --additional-suffix=.chunk --suffix-length=1 temp/rootfs.chunk temp/rootfs-

      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: temp
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_id }}

  Build: # short name because GH will expand with the matrix values
    needs: [ Prepare ]
    runs-on: ubuntu-20.04
    timeout-minutes: 480
    strategy:
      max-parallel: 5
      fail-fast: false # let other jobs try to complete if one fails
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - part: 0

    steps:
      - name: Install depen
        run: sudo apt-get -y install parallel jq axel
      - name: Cache Gradle packages
        uses: actions/cache@v2
        env:
          cache-name: cache-build
        with:
          path: temp
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.run_id }}

      - name: Download part
        run: |

          set +e
          wget https://imola.armbian.com/dl/_rootfs/bullseye-cli-arm64.374a5f4cc9afba3016111ae833345bc9.tar.lz4.list
      - name: Upload artefacts
        if: ${{ env.UPLOAD == 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.tar*"
          tag: "abc/archive"
          overwrite: true
          file_glob: true
          body: "This is Armbian file mirror at Github"
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: mirror.log

