name: Builz
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Docker Image CI
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin   
     - name: Build the tagged Docker image
       run: |
        echo "latest" > VERSION
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no"        
     - name: Push the tagged Docker image
       run: docker push armbian/build:latest
